### ISSUE TITLE
A/libc﹕ Fatal signal 11 (SIGSEGV), code 2, fault addr 0x3fecccd4 in tid 14215  

### ISSUE THREAD

**Issue by TonyTangAndroid** [promeG/XLog#10]
Hi PromeG,

I had used XLog for a little while and it had been great until I upgrade my Android Studio 1.3.o with gradle veresion 1.3.0 and targert to API 23. 

Here is the error message that may help you in resolving this issue.

08-22 18:10:58.225    3648-3648/com.tony.demo D/MultiDexHelper﹕ class not found: com.facebook.share.widget.ShareDialog
08-22 18:10:58.247    3648-3648/com.tony.demo W/nalizableReferenceQueue﹕ Could not load Finalizer in its own class loader.Loading Finalizer in the current class loader instead. As a result, you will not be ableto garbage collect this class loader. To support reclaiming this class loader, eitherresolve the underlying issue, or move Google Collections to your system class path.
    java.io.FileNotFoundException: com/google/common/base/internal/Finalizer.class
            at com.google.common.base.FinalizableReferenceQueue$DecoupledLoader.getBaseUrl(FinalizableReferenceQueue.java:311)
            at com.google.common.base.FinalizableReferenceQueue$DecoupledLoader.loadFinalizer(FinalizableReferenceQueue.java:295)
            at com.google.common.base.FinalizableReferenceQueue.loadFinalizer(FinalizableReferenceQueue.java:214)
            at com.google.common.base.FinalizableReferenceQueue.<clinit>(FinalizableReferenceQueue.java:138)
            at java.lang.Class.classForName(Native Method)
            at java.lang.Class.forName(Class.java:309)
            at com.taobao.android.dexposed.ClassUtils.getClass(ClassUtils.java:461)
            at com.taobao.android.dexposed.ClassUtils.getClass(ClassUtils.java:527)
            at com.taobao.android.dexposed.ClassUtils.getClass(ClassUtils.java:510)
            at com.github.promeg.xlog_android.lib.MultiDexHelper.getAllXLogClasses(MultiDexHelper.java:123)
            at com.github.promeg.xlog_android.lib.MultiDexHelper.getAllMethodsWithAnnoation(MultiDexHelper.java:199)
            at com.github.promeg.xlog_android.lib.XLogConfig.hookAllMethods(XLogConfig.java:60)
            at com.github.promeg.xlog_android.lib.XLogConfig.config(XLogConfig.java:53)
            at com.whatever.ui.activity.AndroidApplication.initLogger(AndroidApplication.java:45)
            at com.whatever.ui.activity.AndroidApplication.onCreate(AndroidApplication.java:41)
            at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4553)
            at android.app.ActivityThread.access$1500(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
08-22 18:10:58.248    3648-3648/com.tony.demo I/Finalizer﹕ Couldn't access Thread.inheritableThreadLocals. Reference finalizer threads will inherit thread local values.
08-22 18:10:58.752    3648-3648/com.tony.demo I/art﹕ Rejecting re-init on previously-failed class java.lang.Class<com.promegu.xlog.processor.XLogProcessor>
08-22 18:10:58.752    3648-3648/com.tony.demo I/art﹕ Rejecting re-init on previously-failed class java.lang.Class<com.promegu.xlog.processor.XLogProcessor>
08-22 18:10:58.754    3648-3648/com.tony.demo D/MultiDexHelper﹕ class not found: com.promegu.xlog.processor.XLogProcessor
08-22 18:11:01.068    3648-3648/com.tony.demo D/MultiDexHelper﹕ getAllMethodsWithAnnoation() called with context = [com.whatever.ui.activity.AndroidApplication@7c22ed8], annoationClass = [interface com.promegu.xlog.base.XLog], xLogSetting = [com.promegu.xlog.base.XLogSetting@e34fb0d]  time: 3495
08-22 18:11:01.073    3648-3648/com.tony.demo I/art﹕ dexposed: >>> hookMethodNative
08-22 18:11:01.073    3648-3648/com.tony.demo A/libc﹕ Fatal signal 11 (SIGSEGV), code 2, fault addr 0x3fecccd4 in tid 3648

**Comment by promeG** [comment]
Hi Tony,

Thank you to report this problem. I'll try to reproduce it and try to  find a better way to traverse classes.

**Comment by promeG** [comment]
@TonyTangAndroid 
Could you please share your build.gradle and XLog settings( methods and classes with @XLog )?

**Comment by promeG** [comment]
Can be fixed by disable proguard.
